TrainingManagementSystem/Models/Batch.cs
namespace TrainingManagementSystem.Models
{
    public class Batch
    {
        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public string Trainer { get; set; }
        public DateTime StartDate { get; set; }
        public int CourseId { get; set; }
        public Course Course { get; set; }
    }
}

TrainingManagementSystem/Models/Course.cs
namespace TrainingManagementSystem.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }  
        public string CourseDescription { get; set; }
        public int Duration { get; set; }
    }
}

TrainingManagementSystem/Models/ErrorViewModel.cs
namespace TrainingManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TrainingManagementSystem/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace TrainingManagementSystem.Models
{
    public enum Role { 
        Manager=1,
        Employee=2
    }
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }   
        public string Password { get; set; }    
        public bool IsActive { get; set; }
        public Role Role { get; set; }
        public int? ManagerId { get; set; }
        public virtual User? Manager { get; set; }
    }
}

TrainingManagementSystem/Controllers/BatchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using TrainingManagementSystem.Context;
using TrainingManagementSystem.Models;

namespace TrainingManagementSystem.Controllers
{
    public class BatchController : Controller
    {
        TrainingDbContext _context;
        public BatchController(TrainingDbContext trainingDbContext) { 
        _context = trainingDbContext;
        }
        public IActionResult Index()
        {
            var list = from batch in _context.Batches
                       join course in _context.Courses
                       on batch.CourseId
                       equals course.CourseId
                       select new BatchViewModel
                       {
                           CourseName = course.CourseName,
                           BatchName = batch.BatchName,
                           Trainer = batch.Trainer,
                           StartDate = batch.StartDate,
                       };


            return View(list.ToList());
        }

        public IActionResult Create() {
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseName");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Batch batch) {

                _context.Batches.Add(batch);
                _context.SaveChanges();
                return RedirectToAction("Index");

        }
    }

    public class BatchViewModel
    {
        [Key]
        public string BatchId { get; set; }
        public string BatchName { get; set; }
        public string CourseName { get; set; }
        public string Trainer { get; set; }
        public DateTime StartDate { get; set; }
    }
}

TrainingManagementSystem/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using TrainingManagementSystem.Context;
using TrainingManagementSystem.Models;

namespace TrainingManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        TrainingDbContext _context;
        public CourseController(TrainingDbContext trainingDbContext) {
            _context = trainingDbContext;
        }
        public IActionResult Index()
        {
            return View(_context.Courses.ToList());
        }

        public IActionResult Details(int? id) {
            Course course = _context.Courses.Find(id);
            return View(course);
        }

        public IActionResult Delete(int id)
        {
            Course course = _context.Courses.Find(id);
            _context.Courses.Remove(course);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Create() {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Course course)
        {
            if (ModelState.IsValid) { 
            _context.Courses.Add(course);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            Course course = _context.Courses.Find(id);
            return View(course);
        }

        [HttpPost]
        public IActionResult Edit(Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Courses.Update(course);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

TrainingManagementSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TrainingManagementSystem.Models;

namespace TrainingManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TrainingManagementSystem/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace TrainingManagementSystem.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TrainingManagementSystem/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;
using System.Collections.Generic;
using TrainingManagementSystem.Context;
using TrainingManagementSystem.Models;

namespace TrainingManagementSystem.Controllers
{
    public class UserController : Controller
    {
        TrainingDbContext _context;
        public UserController(TrainingDbContext trainingDbContext) {
        _context = trainingDbContext;
        }
        public IActionResult Index()
        {

            return View(_context.Users.Where(x => (int)x.Role != 0).ToList()) ;
        }

        public IActionResult Create() {
            ViewData["ManagerId"] = new SelectList(_context.Users.Where(x => (int)x.Role == 1), "Id", "Name");

            return View();
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            if (ModelState.IsValid) {
                _context.Users.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public IActionResult Edit(int? id)
        {
            ViewData["managerid"] = new SelectList(_context.Users.Where(x => (int)x.Role == 1), "Id", "Name", null);
            User user = _context.Users.Find(id);
            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                _context.Users.Update(user);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public IActionResult Details(int? id)
        {
            User user = _context.Users.Find(id);
            return View(user);
        }

        public IActionResult Delete(int? id)
        {
            User user = _context.Users.Find(id);
            if (user != null)
            {
                user.IsActive = false;
                _context.SaveChanges();
            }
            return View("Index");
        }
    }
}

TrainingManagementSystem/Views/Batch/Create.cshtml
@model TrainingManagementSystem.Models.Batch

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Batch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BatchName" class="control-label"></label>
                <input asp-for="BatchName" class="form-control" />
                <span asp-validation-for="BatchName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trainer" class="control-label"></label>
                <input asp-for="Trainer" class="form-control" />
                <span asp-validation-for="Trainer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingManagementSystem/Views/Batch/Index.cshtml
@model IEnumerable<TrainingManagementSystem.Controllers.BatchViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BatchName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trainer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BatchName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trainer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BatchId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BatchId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BatchId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TrainingManagementSystem/Views/Course/Create.cshtml
@model TrainingManagementSystem.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseDescription" class="control-label"></label>
                <input asp-for="CourseDescription" class="form-control" />
                <span asp-validation-for="CourseDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingManagementSystem/Views/Course/Details.cshtml
@model TrainingManagementSystem.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CourseId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TrainingManagementSystem/Views/Course/Edit.cshtml
@model TrainingManagementSystem.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CourseId" />
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseDescription" class="control-label"></label>
                <input asp-for="CourseDescription" class="form-control" />
                <span asp-validation-for="CourseDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingManagementSystem/Views/Course/Index.cshtml
@model IEnumerable<TrainingManagementSystem.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CourseId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CourseId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CourseId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TrainingManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TrainingManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainingManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrainingManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrainingManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Batch" asp-action="Index">Batches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TrainingManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrainingManagementSystem/Views/User/Create.cshtml
@model TrainingManagementSystem.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role"
                        asp-items="Html.GetEnumSelectList<Role>()"></select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manager" class="control-label"></label>
                <select asp-for="ManagerId" class="form-control" asp-items=ViewBag.ManagerId></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingManagementSystem/Views/User/Details.cshtml
@model TrainingManagementSystem.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TrainingManagementSystem/Views/User/Edit.cshtml
@model TrainingManagementSystem.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role"
                        asp-items="Html.GetEnumSelectList<Role>()"></select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manager" class="control-label"></label>
                <select asp-for="ManagerId" class="form-control" asp-items="ViewBag.ManagerId"></select>
                <span asp-validation-for="ManagerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingManagementSystem/Views/User/Index.cshtml
@model IEnumerable<TrainingManagementSystem.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manager.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>